# Site settings
title: My Blog
email: jgould30@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll website on github.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jayg30.github.io/" # the base hostname & protocol for your site
github_username:  JayG30
highlighter: rouge
encoding: utf-8
# Build settings
markdown: kramdown

